### ISSUE TITLE
Standard clinical scans

### ISSUE THREAD

**Issue by KirstieJane** [bids-bep001/bids-specification#1]
At the moment we are proposing 3 groups of anatomical MRI sufficies:

1. Conventional MRI suffixes
2. Grouping suffixes
3. Quantitative MRI (qMRI) map suffixes

I'm chatting with @agahkarakuzu and we're not sure how to describe the `PDT2` and `angio` scans (see the [currently rendered table](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html) in the specification).

The action here is to get a better description from - eg Tom Nichols - to clarify that change.

**Comment by Gilles86** [comment]
@agahkarakuzu will put `PDT2` in the 'conventional scans' section.

The precise meaning of `angio` is unclear to us. It seems a very specific use-case that is not necessarily part of the qMRI-domain.

**Comment by agahkarakuzu** [comment]
Addressed in #37.
