### ISSUE TITLE
Way a qMRI map is obtained

### ISSUE THREAD

**Issue by ChristophePhillips** [bids-bep001/bids-specification#29]
In the "Management of the qMRI maps" [section](https://github.com/bids-bep001/bids-specification/blob/RF_fieldmaps/src/99-appendices/10-qmri.md#management-of-the-qmri-maps), it is stated:
> 1. The qMRI map is calculated at the scanner site through a non-transparent vendor pipeline.
> 2. The qMRI map is generated off-site using an open-source software.

Is the external solution necessarily open-source ? And to some extent using a Docker version of an open-source does not guarantee it is transparent (quite the contrary).
Then what if some open-source solution is integrated in the scanner console or could be considered by the end-user as "part of the scanner equipment"? For example, I hope that at some point in the not-too-distant future, the qMRI maps could be reconstructed by something like the [Gadegetron](https://www.opensourceimaging.org/project/gadgetron/). 

➡️ isn't the dichotomy proposed a bit too restrictive?

**Comment by Gilles86** [comment]
1. The qMRI map is calculated at the scanner site through a vendor pipeline.
2. The qMRI map are generated outside of the scanner software/infrastructure.

**Comment by ChristophePhillips** [comment]
Ha, I should have looked the other way. :wink:

Since the key issue if about the presence or not of the original "raw" images from which the qMRI maps are derived from, I would then state it like this:

> 1. "Pre-generated" qMRI maps. The qMRI maps are generated, e.g. at the scanner site, and only these are available (or saved) in the data set for further processing;
> 2.  "Post-generated" qMRI maps. The qMRI maps are generated from the original multi-contrast images through a third-party software.

What do you of this?

**Comment by Gilles86** [comment]
So what about the use-case I know best: the Siemens MP2RAGE implementation spits out both magnitude/phase images for the 2 inversions **and** the `T1UNI` and `T1map`. These `T1UNI` and `T1map` don't fit in definition 1, because the two raw images are still available. However, the maps were generated at the scanner and many users would right now not be able to generate them again from the raw data.

**Comment by ChristophePhillips** [comment]
True.

But in the case where both 'original' data and (pre-generated) qMRI maps are available how would you organize your data?
- original images in the subjects's `anat` folder and the qMRI maps in the `derivatives`, or
- both original images and qMRI maps in the subjects's `anat` folder

The former would not make end-user happy and require some symbolic linking. I prefer the latter even if it would be a bit odd to keep both, raw and maps, in the same folder. 

Then maybe:
> - "Pre-generated" qMRI maps. The qMRI maps are generated, e.g. at the scanner site, and immediately available;
> - "Post-generated" qMRI maps. The qMRI maps are generated from the original multi-contrast images after the construction of the data set.

**Comment by agahkarakuzu** [comment]
Let's finalize this discussion on #37. Thanks!
