### ISSUE TITLE
QSM not yet included

### ISSUE THREAD

**Issue by Gilles86** [bids-bep001/bids-specification#3]
I think QSM is currently not covered in our draft. I think this should definitely be added.

**Comment by Gilles86** [comment]
@Gilles86 is going to draft something before next week.

**Comment by Gilles86** [comment]
@agahkarakuzu will upload some QSM data.

**Comment by Gilles86** [comment]
QSM has now been incorporated
https://github.com/bids-bep001/bids-specification/pull/27

@agahkarakuzu , any news on open QSM data?

**Comment by agahkarakuzu** [comment]
@Gilles86 I'm on it, I'll just upload a chimap

**Comment by Gilles86** [comment]
Has been addressed in pull #27, also, OSF now includes a QSM dataset.
